# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
import pandas as pd

# your code here
data = pd.read_csv('tic-tac-toe.csv')
data.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [2]:
df = pd.get_dummies(data, drop_first=True)
df.head()

,class,TL_o,TL_x,TM_o,TM_x,TR_o,TR_x,ML_o,ML_x,MM_o,MM_x,MR_o,MR_x,BL_o,BL_x,BM_o,BM_x,BR_o,BR_x
0,True,0,1,0,1,0,1,0,1,1,0,1,0,0,1,1,0,1,0
1,True,0,1,0,1,0,1,0,1,1,0,1,0,1,0,0,1,1,0
2,True,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,0,1
3,True,0,1,0,1,0,1,0,1,1,0,1,0,1,0,0,0,0,0
4,True,0,1,0,1,0,1,0,1,1,0,1,0,0,0,1,0,0,0

In [3]:
# Alternate (unused) function to convert our categorical data to ordinal
def convert_column_to_integer(col):
    new_col = []
    for value in list(df[col]):
        if value == "x":
            new_col.append(0)
        elif value == "o":
            new_col.append(1)
        elif value == "b":
            new_col.append(2)
        else:
            print("ERROR")
    return new_col

# Convert all columns to integer, except the 'class' column
#for col in df.columns:
    #if col != "class":
        #df[col] = convert_column_to_integer(col)

In [4]:
import numpy as np

# Convert the class column
df['class'] = np.where(df['class'] == True, 1, 0)
df.head()

,class,TL_o,TL_x,TM_o,TM_x,TR_o,TR_x,ML_o,ML_x,MM_o,MM_x,MR_o,MR_x,BL_o,BL_x,BM_o,BM_x,BR_o,BR_x
0,1,0,1,0,1,0,1,0,1,1,0,1,0,0,1,1,0,1,0
1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,0,1,1,0
2,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,0,1
3,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,0,0,0,0
4,1,0,1,0,1,0,1,0,1,1,0,1,0,0,0,1,0,0,0

In [5]:
inputs = df.drop('class', axis=1).astype(float).values
outputs = df['class'].astype(float).values

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [6]:
from sklearn.model_selection import train_test_split
import tensorflow as tf

# 1. Split the training and test data.
X_train, X_test, Y_train, Y_test = train_test_split(inputs, outputs, test_size = 0.2)

#X_train = tf.keras.utils.normalize(X_train, axis=1)
#X_test = tf.keras.utils.normalize(X_test, axis=1)

## Alternate method to split the data:

#last_training_index = int(df.shape[0]*0.8)
#X_train = inputs.iloc[0:last_training_index].astype(float).values
#Y_train = outputs.iloc[0:last_training_index].astype(float).values
#first_testing_index = last_training_index + 1
#X_test = inputs.iloc[first_testing_index:].astype(float).values
#Y_test = outputs.iloc[first_testing_index:].astype(float).values

In [7]:
# 2. Create a Sequential model.
model = tf.keras.models.Sequential()

In [8]:
# 3. Add several layers to your model.
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation=tf.nn.softmax))

WARNING: Logging before flag parsing goes to stderr.
W0801 14:37:09.480079 4559046080 deprecation.py:506] From /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [9]:
# 4. Compile the model using adam as the optimizer and sparse_categorical_crossentropy
# as the loss function.
model.compile(optimizer = 'adam', \
              loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [10]:
# 5. Fit the training data.
model.fit(X_train, Y_train, epochs=20)

Epoch 1/20
766/766 [==============================] - 0s 195us/sample - loss: 1.2829 - acc: 0.6175
Epoch 2/20
766/766 [==============================] - 0s 101us/sample - loss: 0.5905 - acc: 0.7037
Epoch 3/20
766/766 [==============================] - 0s 96us/sample - loss: 0.5238 - acc: 0.7441
Epoch 4/20
766/766 [==============================] - 0s 95us/sample - loss: 0.4744 - acc: 0.7872
Epoch 5/20
766/766 [==============================] - 0s 84us/sample - loss: 0.4236 - acc: 0.8211
Epoch 6/20
766/766 [==============================] - 0s 103us/sample - loss: 0.3673 - acc: 0.8512
Epoch 7/20
766/766 [==============================] - 0s 84us/sample - loss: 0.2885 - acc: 0.9217
Epoch 8/20
766/766 [==============================] - 0s 97us/sample - loss: 0.2085 - acc: 0.9765
Epoch 9/20
766/766 [==============================] - 0s 94us/sample - loss: 0.1504 - acc: 0.9856
Epoch 10/20
766/766 [==============================] - 0s 92us/sample - loss: 0.1152 - acc: 0.9883
Epoch 11/20
766/766 [==============================] - 0s 94us/sample - loss: 0.0845 - acc: 0.9856
Epoch 12/20
766/766 [==============================] - 0s 111us/sample - loss: 0.0688 - acc: 0.9869
Epoch 13/20
766/766 [==============================] - 0s 134us/sample - loss: 0.0532 - acc: 0.9883
Epoch 14/20
766/766 [==============================] - 0s 105us/sample - loss: 0.0397 - acc: 0.9935
Epoch 15/20
766/766 [==============================] - 0s 101us/sample - loss: 0.0350 - acc: 0.9961
Epoch 16/20
766/766 [==============================] - 0s 87us/sample - loss: 0.0309 - acc: 0.9935
Epoch 17/20
766/766 [==============================] - 0s 118us/sample - loss: 0.0292 - acc: 0.9961
Epoch 18/20
766/766 [==============================] - 0s 159us/sample - loss: 0.0220 - acc: 0.9974
Epoch 19/20
766/766 [==============================] - 0s 125us/sample - loss: 0.0187 - acc: 1.0000
Epoch 20/20
766/766 [==============================] - 0s 94us/sample - loss: 0.0198 - acc: 0.9987

In [11]:
# 6. Evaluate your neural network model with the test data.
val_loss, val_acc = model.evaluate(X_test, Y_test)

192/192 [==============================] - 0s 293us/sample - loss: 0.0462 - acc: 0.9792

In [12]:
# 7. Save the model
model.save('tic_tac_toe.model')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [13]:
import random

# your code here
new_model = tf.keras.models.load_model('tic_tac_toe.model')
predictions = new_model.predict(X_test)

for i in random.sample(range(1, 100), 10):
    print("Prediction:", np.argmax(predictions[i]))

W0801 14:37:11.991540 4559046080 deprecation.py:506] From /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0801 14:37:11.993772 4559046080 deprecation.py:506] From /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:97: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0801 14:37:12.220145 4559046080 hdf5_format.py:263] Sequential models without an `input_shape` passed to the first layer cannot reload their optimizer state. As a result, your model isstarting with a freshly initialized optimizer.

Prediction: 1
Prediction: 0
Prediction: 1
Prediction: 1
Prediction: 1
Prediction: 1
Prediction: 0
Prediction: 0
Prediction: 1
Prediction: 0

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [14]:
# your code here

**Which approach(es) did you find helpful to improve your model performance?**

In [15]:
# your answer here